run:
  # Run several linters by default
  linters:
    enable:
      - govet
      - errcheck
      - staticcheck
      - gosimple
      - ineffassign
      - structcheck
      - varcheck
      - deadcode
      - gofmt
      - goimports
      - misspell
      - unused

issues:
  # Exclude some common false positive issues
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - golint
      text: "should have comment or be unexported"

linters-settings:
  gofmt:
    simplifications: true
  goimports:
    local-prefixes: github.com/apaliavy/cloudbuild-experiments
  misspell:
    locale: US
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    shadow: true

# Optional: Specify directories to include/exclude
# paths:
#   include:
#     - cmd/
#     - pkg/
#   exclude:
#     - vendor/

# Timeout for the whole process
# Default is 1 minute
timeout: 2m
